# Generated by Django 6.0.4 on 2026-04-24 01:37

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la prenda')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='prendas/', validators=[catalogo.models.validar_imagen_segura], verbose_name='Imagen principal')),
                ('es_nuevo', models.BooleanField(default=False, verbose_name="Mostrar en 'Nuevo'")),
                ('es_popular', models.BooleanField(default=False, verbose_name="Mostrar en 'Popular'")),
                ('temporada', models.CharField(choices=[('verano', 'Verano'), ('invierno', 'Invierno'), ('todo', 'Todo el año')], default='todo', max_length=20, verbose_name='Temporada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
