# Generated by Django 6.0.4 on 2026-04-24 04:03

import catalogo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('activa', models.BooleanField(default=True, verbose_name='Visible en el catálogo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='prenda',
            name='temporada',
        ),
        migrations.AddField(
            model_name='prenda',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Visible en catálogo'),
        ),
        migrations.AddField(
            model_name='prenda',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='es_nuevo',
            field=models.BooleanField(default=False, verbose_name="Badge 'Nuevo' (dorado)"),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='es_popular',
            field=models.BooleanField(default=False, verbose_name="Badge 'Popular' (blanco)"),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen',
            field=models.ImageField(upload_to='prendas/', validators=[catalogo.models.validar_imagen_segura]),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='prenda',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas', to='catalogo.categoria'),
        ),
    ]
